# Generated by Django 3.2.9 on 2022-10-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000)),
                ('date', models.DateField(max_length=500, null=True)),
                ('circular_name', models.FileField(upload_to='files/')),
            ],
        ),
    ]
