# Generated by Django 3.2.9 on 2022-09-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_price', models.FloatField(max_length=1000)),
                ('published_date', models.DateField(max_length=200)),
                ('Services', models.TextField(max_length=200)),
                ('price_list', models.FileField(max_length=200, upload_to='')),
            ],
        ),
    ]
