# Generated by Django 3.2.9 on 2022-09-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investigations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='Services',
        ),
        migrations.RemoveField(
            model_name='price',
            name='investigation_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='price',
            name='price_list',
            field=models.FileField(upload_to='download/'),
        ),
    ]
