# Generated by Django 3.2.9 on 2022-09-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investigations', '0002_auto_20220925_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_list',
            field=models.FileField(upload_to='download2/'),
        ),
    ]
