# Generated by Django 3.2.9 on 2022-10-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='heading',
            field=models.CharField(default='National Institute of Laboratory Medicine & Referral Centre andtraining center', max_length=1000),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default='Contact us', max_length=1000),
        ),
    ]
