# Generated by Django 3.2.9 on 2022-09-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('title', models.TextField(max_length=1000)),
                ('download_link', models.FileField(max_length=500, upload_to='images/')),
            ],
        ),
    ]
