# Generated by Django 3.2.9 on 2022-09-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0003_alter_publication_download_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='download_link',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
